name: Validate and Generate App List

on:
  push:
    paths:
      - "apks/**"

jobs:
  validate-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install glob

      - name: Run validation and generator
        run: node .github/scripts/validate-and-generate.js

      - name: Commit and push if changed
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if [[ `git status --porcelain` ]]; then
            git add app.list.json
            git commit -m "Update app.list.json"

            # Use token-based authentication
            git remote set-url origin https://x-access-token:${ACCESS_TOKEN}@github.com/${{ github.repository }}
            git push origin HEAD:${{ github.ref }}
          fi
